export const CREATE_SHOP_START = "CREATE_SHOP_START";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";
export const CREATE_SHOP_FAIL = "CREATE_SHOP_FAIL";
export const FETCH_SHOPS_START = "FETCH_SHOPS_START";
export const FETCH_SHOPS_SUCCESS = "FETCH_SHOPS_SUCCESS";
export const FETCH_SHOPS_FAIL = "FETCH_SHOPS_FAIL";

export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const FETCH_CURRENT_LOCATION = "FETCH_CURRENT_LOCATION";
export const FETCH_CURRENT_LOCATION_ERROR = "FETCH_CURRENT_LOCATION_ERROR";
